### ISSUE TITLE
Can not run anything if preceding folders have spaces

### ISSUE THREAD

**Issue by markosbg** [rabix/bunny#387]
Clone repo into path, which have folders, with spaces for their name:
e.g. 

`/Users/marko/code/else/folder with space/bunny/rabix-cli/target/rabix-cli-1.0.3`

Try to run job from examples folder.

Result:
```
./rabix examples/dna2protein/dna2protein.cwl.json examples/dna2protein/inputs.json -v
[2017-11-27 17:10:13.951] [DEBUG] [main] o.r.c.BackendCommandLine [BackendCommandLine.java:590] Config path: /Users/marko/code/else/folder%20with%20space/bunny/rabix-cli/target/rabix-cli-1.0.3/config
[2017-11-27 17:10:13.955] [INFO] [main] o.r.c.BackendCommandLine [BackendCommandLine.java:599] Config directory doesn't exist or is not a directory
```

**Comment by milos-ljubinkovic** [comment]
Should be fixed in the latest release

**Comment by ivanbatic** [comment]
Tried this with 1.0.4 and it is still an issue.
Scenario:
- Download the release, unzip (`rabix-cli-1.0.4`)
- Rename to `rabix-cli 1.0.3`, `cd` into it
- Running rabix through shell script, jar, relative or absolute path shows the help info and doesn't run the app. Works if containing directory has no spaces.

**Comment by milos-ljubinkovic** [comment]
Sorry about that, turns out this is still an issue when the config path is in a folder with spaces which I didn't test. WIll make an updated release now.

**Comment by milos-ljubinkovic** [comment]
Can you confirm it is fixed in the 1.0.4-2 release?
