### ISSUE TITLE
Symbolic link to the binary does not work

### ISSUE THREAD

**Issue by mattions** [rabix/bunny#76]
It's not possible to symlink the binary right now:

```
mattions@apollo:bin$ ls -l
total 4020
lrwxrwxrwx 1 mattions mattions      48 Dec 12 13:54 rabix -> /home/mattions/SBG/Progs/rabix-0.7.0-alpha/rabix

mattions@apollo:bin$ rabix
Error: Unable to access jarfile /home/mattions/bin/lib/rabix-backend-local.jar
```

**Comment by StarvingMarvin** [comment]
This should be fixed in a latest release. Can you please verify if it works, so we could close this issue.

**Comment by mattions** [comment]
RC1 still does not work using a symlink.
Rabix runs, but it gets confused on the file path

If launched from where the binary is it works: 

```
mattions@apollo:rabix-backend-local-1.0.0-SNAPSHOT$ ./rabix examples/dna2protein/dna2protein.cwl.json -- --input_file examples/dna2protein/data/input.txt 
[2016-12-14 10:14:53.833] Pulling docker image rfranklin/pythondev:latest
[2016-12-14 10:14:56.085] Running command line: python transcribe_argparse.py -d /home/mattions/SBG/Progs/rabix-backend-local-1.0.0-SNAPSHOT/examples/dna2protein/data/input.txt --verbose > rna.txt
[2016-12-14 10:14:56.533] Job root.Transcribe has started
[2016-12-14 10:14:59.674] Job root.Transcribe has completed
[2016-12-14 10:14:59.907] Pulling docker image rfranklin/pythondev:latest
[2016-12-14 10:15:01.289] Running command line: python translate.py -r /home/mattions/SBG/Progs/rabix-backend-local-1.0.0-SNAPSHOT/486da912-a610-449b-ac66-f89c87d27f41/root/Transcribe/rna.txt > protein.txt
[2016-12-14 10:15:01.737] Job root.Translate has started
[2016-12-14 10:15:04.875] Job root.Translate has completed
{
  "output_protein" : {
    "checksum" : "sha1$55adf0ec2ecc6aee57a774d48216ac5a97d6e5ba",
    "class" : "File",
    "location" : "/home/mattions/SBG/Progs/rabix-backend-local-1.0.0-SNAPSHOT/486da912-a610-449b-ac66-f89c87d27f41/root/Translate/protein.txt",
    "name" : "protein.txt",
    "path" : "/home/mattions/SBG/Progs/rabix-backend-local-1.0.0-SNAPSHOT/486da912-a610-449b-ac66-f89c87d27f41/root/Translate/protein.txt",
    "secondaryFiles" : [ ],
    "size" : 9
  }
}
```

If launched from a symlink (`/home/mattions/bin/rabix`) it fails:
```
mattions@apollo:bin$ ./rabix /home/mattions/SBG/Progs/rabix-backend-local-1.0.0-SNAPSHOT/examples/dna2protein/dna2protein.cwl.json -- --input_file /home/mattions/SBG/Progs/rabix-backend-local-1.0.0-SNAPSHOT/examples/dna2protein/data/input.txt 
[2016-12-14 10:18:45.548] Pulling docker image rfranklin/pythondev:latest
[2016-12-14 10:18:48.068] Running command line: python transcribe_argparse.py -d /home/mattions/SBG/Progs/rabix-backend-local-1.0.0-SNAPSHOT/examples/dna2protein/data/input.txt --verbose > rna.txt
[2016-12-14 10:18:48.595] Job root.Transcribe has started
[2016-12-14 10:18:49.798] Job 3645728d-0a47-4ba3-bccb-abb9cc70d392 failed with exit code 2.
[2016-12-14 10:18:50.144] Failed to execute a Job
```

This is the job.err
```
mattions@apollo:bin$ cat 92dca274-481c-4e5d-8df2-346aecf18307/root/Transcribe/job.err.log 
usage: transcribe_argparse.py [-h] [-d DNA] [-v]
transcribe_argparse.py: error: argument -d/--dna: can't open '/home/mattions/SBG/Progs/rabix-backend-local-1.0.0-SNAPSHOT/examples/dna2protein/data/input.txt': [Errno 2] No such file or directory: '/home/mattions/SBG/Progs/rabix-backend-local-1.0.0-SNAPSHOT/examples/dna2protein/data/input.txt'
```

Note that the file is there:

```
mattions@apollo:bin$ ls -lh /home/mattions/SBG/Progs/rabix-backend-local-1.0.0-SNAPSHOT/examples/dna2protein/data/input.txt
-rw-r--r-- 1 mattions mattions 29 Nov 29 19:16 /home/mattions/SBG/Progs/rabix-backend-local-1.0.0-SNAPSHOT/examples/dna2protein/data/input.txt
```

Lateral thoughts on the release:
Two little feedback:
- I would prefer to have it call just `rabix-backend-local-1.0.0-RC` instead of `rabix-backend-local-1.0.0-SNAPSHOT`, so we always have the version
- the rabix command inside the folder should be executable in the folder (now it's not)

**Comment by StarvingMarvin** [comment]
Honestly, I'm not sure what was wrong because I couldn't reproduce it. I've added a test that tests running rabix both directly and through symlink. Rc2 fixes other issues (directory name and +x permission), so please check it out.

**Comment by mattions** [comment]
@StarvingMarvin I've downloaded the rc-2

This time I can launch a cwl job with files and input not in the directory where rabix is:

```
mattions@apollo:rabix-1.0.0-rc2$ ./rabix ~/SBG/code/dna2protein/dna2protein.cwl.json -- --dna ~/SBG/code/dna2protein/dna.txt
[2016-12-16 14:32:22.807] [INFO] Pulling docker image sevenbridges/dna2protein:0.5.3
[2016-12-16 14:32:24.684] [INFO] Running command line: transcribe.py /home/mattions/SBG/code/dna2protein/dna.txt > transcribe.log
[2016-12-16 14:32:25.074] [INFO] Job root.transcribe has started
[2016-12-16 14:32:26.265] [ERROR] Job 66afc4ff-3162-4f2f-9f1a-1240525b52ca failed with exit code 2.
[2016-12-16 14:32:26.266] [INFO] Job 66afc4ff-3162-4f2f-9f1a-1240525b52ca failed with exit code 2.
[2016-12-16 14:32:27.190] [INFO] Failed to execute a Job
```

The job error
```
mattions@apollo:rabix-1.0.0-rc2$ cat dc1b8d30-f348-43dc-a1ad-133bf0cfbf4b/root/transcribe/job.err.log 
usage: transcribe.py [-h] [-v] [--version] dna
transcribe.py: error: argument dna: can't open '/home/mattions/SBG/code/dna2protein/dna.txt': [Errno 2] No such file or directory: '/home/mattions/SBG/code/dna2protein/dna.txt'
```

It looks like the file does not get mounted in the proper location in the container?

The symlink didn't try yet

**Comment by StarvingMarvin** [comment]
OK, I created a separate issue for that: #86 so I'll close this one.
